# Generated by Django 5.2.4 on 2025-07-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='iqraa_id',
            field=models.IntegerField(unique=True),
        ),
    ]
