# Generated by Django 5.2.4 on 2025-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NursingModelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqraa_id', models.IntegerField(help_text='6-digit unique identification number', max_length=6, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('nursing_station', models.CharField(max_length=100)),
                ('form_pdf', models.FileField(upload_to='pdfs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
