# Generated by Django 5.2.4 on 2025-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1_assement',
            name='staff',
        ),
        migrations.AlterField(
            model_name='form1_assement',
            name='evaluation_period',
            field=models.CharField(choices=[('INITIAL', '<1 Month (Initial)'), ('THREE_MONTH', '3rd Month'), ('SIX_MONTH', '6th Month'), ('TWELVE_MONTH', '12th Month')], max_length=12),
        ),
    ]
