# Generated by Django 5.2.4 on 2025-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingmodellisting',
            name='statues',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
