# Generated by Django 5.2.4 on 2025-08-06 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_department', '0002_nursingmodellisting_statues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1_assement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('evaluation_period', models.CharField(choices=[('INITIAL', '<1 Month (Initial)'), ('THREE_MONTH', '3rd Month'), ('SIX_MONTH', '6th Month'), ('TWELVE_MONTH', '12th Month')], default='INITIAL', max_length=12)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data', models.JSONField(default=dict)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('evaluator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NursingModelListing',
        ),
        migrations.AddField(
            model_name='form1_assement',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_department.staff'),
        ),
    ]
