# Generated by Django 5.2.4 on 2025-08-15 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_department', '0002_remove_form1_assement_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1_assement',
            name='staff',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_department.staff'),
            preserve_default=False,
        ),
    ]
