# Generated by Django 5.2.4 on 2025-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_department', '0003_form1_assement_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1_assement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
