# Generated by Django 5.2.4 on 2025-08-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('whatapp_number', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Undertermined'), ('T', 'Transgender')], max_length=1)),
                ('patient_type', models.CharField(choices=[('G', 'General'), ('C', 'Camp'), ('CH', 'Card Holder'), ('CO', 'Corporate'), ('CA', 'Cardle'), ('EM', 'Employee'), ('ES', 'ESI')], max_length=2)),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'MRS'), ('MISS', 'Miss'), ('PROF', 'Professor'), ('MSTR', 'Mstr'), ('DR', 'DR')], max_length=4)),
                ('appoinment_date', models.DateField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='front_office.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('Address_line_1', models.CharField(max_length=200)),
                ('Address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('pincode', models.CharField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='front_office.patient_registration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
