# Generated by Django 5.2.4 on 2025-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
    ]
