# Generated by Django 5.2.4 on 2025-08-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front_office.department'),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='doctor_vist',
            field=models.CharField(blank=True, choices=[('MRNG', 'Morning'), ('EVNG', 'Evening')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('Tk', 'Token'), ('BK', 'Booking'), ('NK', 'New Token')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
