# Generated by Django 5.2.4 on 2025-08-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0002_remove_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front_office.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front_office.state'),
        ),
    ]
