# Generated by Django 5.2.4 on 2025-08-19 05:39

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0002_patient_registration_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front_office.doctor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
