# Generated by Django 5.2.4 on 2025-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0003_patient_registration_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='op_consulting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
