# Generated by Django 5.2.4 on 2025-08-24 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0003_alter_address_country_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='appoinment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
