# Generated by Django 5.2.4 on 2025-08-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_office', '0004_doctor_op_consulting_doctor_service_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Doctors_Department',
        ),
        migrations.RenameField(
            model_name='patient_registration',
            old_name='Department',
            new_name='department',
        ),
    ]
